### ISSUE TITLE
doesn't work.

### ISSUE THREAD

**Issue by trvnkwil** [vcyzteen/dotbaka#8]
Your theme looks amazing so i wanted to try it on my machine but it doesn't work. All i get is a wallpaper with no panels/widgets. I installed all the dependencies and followed the installation steps. Can you help me?

**Comment by xealea** [comment]
> Your theme looks amazing so i wanted to try it on my machine but it doesn't work. All i get is a wallpaper with no panels/widgets. I installed all the dependencies and followed the installation steps. Can you help me?

You seem to be missing some packages like `tint2` and `feh` try to install carefully. And if doesn't work again. Try to install the packages one by one

**Comment by xealea** [comment]
> > Your theme looks amazing so i wanted to try it on my machine but it doesn't work. All i get is a wallpaper with no panels/widgets. I installed all the dependencies and followed the installation steps. Can you help me?
> 
> You seem to be missing some packages like `tint2` and `feh` try to install carefully. And if doesn't work again. Try to install the packages one by one

Ah my bad too. because I haven't written `tint2` in the command I made. If there is something missing in a package, just say it here, and thank you for the issue given, because not many people use it, I almost forgot to check the whole thing 😅

**Comment by xealea** [comment]
For now try to install copy and re-paste for the package installation section | https://github.com/vcyzteen/dotbaka#dependency-
